### ISSUE TITLE
cannot find -lX11: No such file or directory

### ISSUE THREAD

**Issue by TouchstoneTheDev** [IvyTheGreat01/tetris_x64_assembly#1]
~/tetris_x64_assembly$ make
gcc -o tetris tetris.o -lX11 -no-pie
/usr/bin/ld: cannot find -lX11: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:8: tetris] Error 1

**Comment by tanmay-sachin-veer** [comment]
Open a terminal.

Run the following command to install the development package for libX11:

`sudo apt-get install libx11-dev`
